Module4 task3
htmlacademy-nodejs/691337-buy-and-sell-3 pull request #12
Opened 2020-05-11 19:07 UTC by honiara1973

2020-05-12 21:05 UTC, html-malex requested changes

2020-05-12 21:05 UTC, html-malex commented on src/express/controllers/main.js
> +const getData = (path) => {
Функция getData() у тебя повторяется практически в каждом контроллере - может, есть смысл вынести ее отдельно, например, в utils?

2020-05-12 21:05 UTC, html-malex commented on src/express/controllers/main.js
> +  return axios.get(path).then((content) => content.data);
И поскольку мы теперь умеем работать с асинхронными функциям - предлагаю заменить `.then()` на нормальный `await` :) И не забывай обрабатывать ошибки, которые могут прийти - например, 404

2020-05-12 21:05 UTC, html-malex commented on src/express/controllers/main.js
> +const getData = (path) => {
И логично везде повторяющийся `http://localhost:3000/api` унести в константы

2020-05-12 21:05 UTC, html-malex commented on src/express/controllers/offers.js
> +    const offerById = await getData(`${url}/${req.params.id}`);
Если объявления с несуществующим id не найдено, то пользователь никак об этом не узнает. НО! У нас же есть шаблон для отображения ошибок ;)

2020-05-12 21:05 UTC, html-malex commented on src/express/templates/main.pug
> +              span.category-tile__qty.js-qty  81
Если не секрет - в чем смысл добавления пробела?

2020-05-14 18:21 UTC, honiara1973 commented on src/express/templates/main.pug
> +              span.category-tile__qty.js-qty  81
Там такая разметка, что количества на названия залазят, очень бросалось в глаза. Поэтому и поставила пробелы.

2020-05-14 20:06 UTC, html-malex commented on src/utils.js
> +    return logger.error(`Error: ${err}`);
1. достаточно вывести err.message, а не весь err
2. возвращать нужно не logger.error, а саму ошибку

2020-05-14 20:13 UTC, html-malex commented on src/express/controllers/main.js
> +    return logger.error(`Error: ${err}`);
Вывод ошибки логгером у тебя уже сделан в `getData()`
Здесь нужно отобразить страницу с ошибкой

2020-05-14 20:13 UTC, html-malex commented on src/express/controllers/my.js
> +    return logger.error(`Error: ${err}`);
Вывод ошибки логгером у тебя уже сделан в `getData()`

2020-05-14 20:14 UTC, html-malex commented on src/express/controllers/my.js
> +    return logger.error(`Error: ${err}`);
Вывод ошибки логгером у тебя уже сделан в `getData()`

2020-05-14 20:14 UTC, html-malex commented on src/express/controllers/offers.js
> +    return logger.error(`${err}`);
Вывод ошибки логгером у тебя уже сделан в `getData()`

2020-05-14 20:22 UTC, html-malex requested changes
Осталось только доработать обработку ошибок

2020-05-17 10:11 UTC, html-malex requested changes
Доработать обработку ошибок (отписался в Telegram)

2020-05-18 19:19 UTC, html-malex approved these changes

2020-05-18 19:19 UTC, merged