Module7 task3
htmlacademy-nodejs/691337-buy-and-sell-3 pull request #21
Opened 2021-02-28 16:24 UTC by honiara1973

2021-03-01 19:50 UTC, html-malex requested changes

2021-03-01 19:50 UTC, html-malex commented on src/service/controllers/user.js
> +module.exports.logout = async (req, res) => {
При выходе удаляется только refresh-токен - почему?

2021-03-04 19:26 UTC, honiara1973 commented on src/service/controllers/user.js
> +module.exports.logout = async (req, res) => {
Да бог его знает. Вообще здесь сначала post-запрос к api, чтобы в базе данных api удалился последний refresh-token (он ведь, насколько я поняла, не имеет срока истекания).  А потом я делаю await res.clearCookie(); чтобы удалить все куки в браузере. Что-то не так работает?

2021-04-18 17:05 UTC, html-malex approved these changes

2021-04-18 17:05 UTC, html-malex commented on src/service/controllers/user.js
> +module.exports.logout = async (req, res) => {
access token нужен, чтобы пользователь авторизовался и мог выполнять нужные запросы. Но у него есть срок "протухания" (у тебя он выставлен в 30 мин), при этом нужно получить новый. Чтобы каждый раз после "протухания" не просить ввести логин/пароль, используется refresh token, который обновляет access token.
Судя по коду, у тебя почему-то сбрасывается только refresh token, а нужно наоборот

Вот неплохая [статья](https://habr.com/ru/company/Voximplant/blog/323160/), которая поможет понять назначение токенов

2021-04-18 17:05 UTC, html-malex commented on src/service/controllers/user.js
> +module.exports.logout = async (req, res) => {
Думаю, у проверяющих потом будут вопросы по этой теме - будь готова. Но окей, пусть будет апрув

2021-04-18 17:06 UTC, merged